print("Hello M.6/11")
print("My name Wanwipha Donjuang")
print("Number 43")
print("อายุ:",17,"ปี")
print("วันเกิด:",27,"สิงหาคม พศ.:",2547,)
print("สัญชาติ:ไทย")
print("โรงเรียน:ชลราษฎรอำรุง")
print("สีที่ชอบ:ดำ")
print("งานอดิเรก:ฟังเพลง")
print("กีฬาที่ชอบ:เปตอง")
#วรรณวิภา ดอนจวง เลขที่ 43